//[example_output
> custom_main
Using custom entry point...
Running 1 test case...
test.cpp(10): error: in "test1": check false has failed

*** 1 failure is detected in the test module "custom_main"
//]