//[example_output
> example
Running 1 test case...
unknown location(0): fatal error in "test_external_interface": signal: integer divide by zero; address of failing instruction: 0x00048090
test.cpp(9): last checkpoint: Calling foo with i=1

*** 1 failures is detected in test suite "example"
//]