//[example_output
> example
Running 1 test case...
test.cpp(8): error in "test": Nothing to test

*** 1 failures is detected in test suite "example"
//]